//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceShoes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favoriler
    {
        public int FavoriId { get; set; }
        public int UrunId { get; set; }
        public int KisiId { get; set; }
    
        public virtual Kisiler Kisiler { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
