//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceShoes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparisler
    {
        public int SiparisId { get; set; }
        public int UrunId { get; set; }
        public System.DateTime SiparisTarihi { get; set; }
        public int KisiId { get; set; }
        public int SepetId { get; set; }
        public decimal SiparisTutar { get; set; }
        public bool SiparisDurum { get; set; }
    
        public virtual Kisiler Kisiler { get; set; }
        public virtual Sepet Sepet { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
